version: '2'
services:
  data:
    image: busybox
    volumes:
      - ./volume:/var/lib/postgresql/data

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes_from:
      - data
    container_name: postgres96